### ISSUE TITLE
Examples crashing with the NatCam

### ISSUE THREAD

**Issue by ricardojmveiga** [EnoxSoftware/NatCamWithOpenCVForUnityExample#2]
All the examples with the NatCam eventually crash the application. Looking at the Debug Profiler it seems a problem with the garbage collector.

**Comment by alexdkt** [comment]
It happens the same to me.

In any of the examples, as soon as you have access to the camera (sometimes after 1 or 2 seconds) the App hangs.

Working with Samsung Galaxy S8
NatCamWithOpenCVForUnityExample_v1.0.2
OpenCV 2.3.2
NatCam 2.0f4
Unity 2018.2.0f2

MONITOR LOG: 

10-24 13:21:12.271: E/RenderScript(22572): rsAssert failed: cmd->cmdID < (sizeof(gPlaybackFuncs) / sizeof(void *)), in frameworks/rs/rsThreadIO.cpp at 148
10-24 13:21:12.271: E/rsC++(22572): RS Error rsForEach called with none-zero inLen with null in allocations
...
10-24 13:21:12.271: E/RenderScript(22572): playCoreCommands error con 0xb825f000, cmd -1149336320
10-24 13:21:12.271: E/rsC++(22572): RS CPP error: Error returned from runtime
10-24 13:21:12.274: E/CRASH(22572): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr a58dc404
...
10-24 13:21:12.881: E/ExynosCameraMemoryAllocator(4971): ERR(alloc):dequeue_buffer failed
10-24 13:21:12.881: E/Surface(4971): queueBuffer: error queuing buffer to SurfaceTexture, -32
10-24 13:21:12.881: E/ExynosCameraMemoryAllocator(4971): ERR(enqueueBuffer):enqueue_buffer failed
10-24 13:21:12.881: E/ExynosCameraBufferManager(4971): [CAM_ID(0)][PREVIEW_BUF]-ERR(m_putBuffer[2492]):could not enqueue_buffer [bufIndex=6]

**Comment by olokobayusuf** [comment]
Hey guys. Developer of NatCam here. We have a fix for this coming in the NatCam 2.1 update. The update will be live sometime next week. Sorry for the inconvenience!

**Comment by olokobayusuf** [comment]
@EnoxSoftware can you check up on this issue? We have fixed the crashing in 2.1.
