### ISSUE TITLE
Update to NatCam 2.1

### ISSUE THREAD

**Issue by olokobayusuf** [EnoxSoftware/NatCamWithOpenCVForUnityExample#3]
@EnoxSoftware I'm working on this right now. I just wanted to let you know.

**Comment by EnoxSoftware** [comment]
Thank you for informing me.  I will update my example project soon.

**Comment by olokobayusuf** [comment]
No need, I'm working on it. I'll submit a PR once I'm done.

**Comment by olokobayusuf** [comment]
See #4

**Comment by EnoxSoftware** [comment]
I updated the NatCamWithOpenCVForUnityExample project to 1.0.3 (Update to NatCam 2.1f3).
Error details that occur on some Android devices are in the following reply.

https://github.com/EnoxSoftware/NatCamWithOpenCVForUnityExample/pull/4#issuecomment-451884069
https://github.com/EnoxSoftware/NatCamWithOpenCVForUnityExample/pull/4#issuecomment-452042851
https://github.com/EnoxSoftware/NatCamWithOpenCVForUnityExample/pull/4#issuecomment-452263273
